server:
  port: 8080
  servlet:
    context-path: /

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/abms
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


# Core PayOS credentials
payos:
  client-id: e42817bc-7d8c-4f72-a776-a51e24ba5058
  api-key: c6fd1c49-89b8-42d7-a9fe-8f837d8416d9
  checksum-key: 71b78e3aa8aff6952a5f1cd693054a20eca17ef8b1c99efb120a55027bb6bdfa

# Logging level: DEBUG | INFO | NONE
  log-level: NONE